USE [Jocuri_Video]
GO

CREATE PROCEDURE deadlock_t1 AS
BEGIN 
	BEGIN TRAN
	BEGIN TRY
		UPDATE Jocuri_Video SET pret = 200 WHERE id_joc = 1
		INSERT INTO log_table VALUES ('UPDATE', 'Jocuri Video', CURRENT_TIMESTAMP)
		WAITFOR DELAY '00:00:05'
		UPDATE Firme SET nume = 'nume', adresa = 'adresa' WHERE id_firma = 1
		INSERT INTO log_table VALUES ('UPDATE', 'Firme', CURRENT_TIMESTAMP)

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		PRINT ERROR_MESSAGE()
	END CATCH
END
GO

CREATE PROCEDURE deadlock_t2 AS
BEGIN 
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	-- SET DEADLOCK_PRIORITY HIGH
	SET DEADLOCK_PRIORITY LOW
	BEGIN TRAN
	BEGIN TRY
		UPDATE Firme SET nume = 'nume2', adresa = 'adresa2' WHERE id_firma = 1
		INSERT INTO log_table VALUES ('UPDATE', 'Firme', CURRENT_TIMESTAMP)

		WAITFOR DELAY '00:00:05'

		UPDATE Jocuri_Video SET pret = 25 WHERE id_joc = 1
		INSERT INTO log_table VALUES ('UPDATE', 'Jocuri Video', CURRENT_TIMESTAMP)

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT ERROR_MESSAGE()
		ROLLBACK TRAN
	END CATCH
END
GO

CREATE PROCEDURE deadlock_t1_c# AS
BEGIN 
	BEGIN TRAN
	UPDATE Jocuri_Video SET pret = 200 WHERE id_joc = 1
	INSERT INTO log_table VALUES ('UPDATE', 'Jocuri Video', CURRENT_TIMESTAMP)
	WAITFOR DELAY '00:00:05'
	UPDATE Firme SET nume = 'nume', adresa = 'adresa' WHERE id_firma = 1
	INSERT INTO log_table VALUES ('UPDATE', 'Firme', CURRENT_TIMESTAMP)

	COMMIT TRAN
END
GO

CREATE PROCEDURE deadlock_t2_c# AS
BEGIN 
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	-- SET DEADLOCK_PRIORITY HIGH
	SET DEADLOCK_PRIORITY LOW
	BEGIN TRAN
	
	UPDATE Firme SET nume = 'nume2', adresa = 'adresa2' WHERE id_firma = 1
	INSERT INTO log_table VALUES ('UPDATE', 'Firme', CURRENT_TIMESTAMP)

	WAITFOR DELAY '00:00:05'

	UPDATE Jocuri_Video SET pret = 25 WHERE id_joc = 1
	INSERT INTO log_table VALUES ('UPDATE', 'Jocuri Video', CURRENT_TIMESTAMP)

	COMMIT TRAN
END
GO

EXEC deadlock_t1
EXEC deadlock_t2

DROP PROCEDURE deadlock_t1
DROP PROCEDURE deadlock_t2