USE [Jocuri Video]

CREATE TABLE Genuri
(
id_gen INT PRIMARY KEY IDENTITY,
nume VARCHAR(50),
PG INT
);

CREATE TABLE Genuri_Jocuri
(
id_joc INT FOREIGN KEY REFERENCES Jocuri_Video(id_joc) ON UPDATE CASCADE ON DELETE CASCADE,
id_gen INT FOREIGN KEY REFERENCES Genuri(id_gen) ON UPDATE CASCADE ON DELETE CASCADE,
PRIMARY KEY(id_joc, id_gen)
);

ALTER TABLE Jocuri_Video
DROP COLUMN gen;

ALTER TABLE Echipe
ADD nume VARCHAR(50);